FROM ubuntu:22.04
RUN apt-get -y update \
 && apt-get install -y nginx \
 && rm /etc/nginx/sites-enabled/default
COPY default.conf /etc/nginx/conf.d/default.conf
COPY nginx-content /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

